from random import randint

words = [] # this will be 370 092 words long

with open("words.txt") as f:
    for line in f:
        a = line.rstrip()
        words.append(a) # words now contains most words of the english language that doesn't have a number or a symbol

password = ""

for i in range(3):
    rand_word = randint(0, len(words)-1) # this randomly generates a number that is an index of words
    password += words[rand_word].capitalize() # this appends the data at the index (generated by rand_word) to password

print(password)
